# Generated by Django 4.1.4 on 2024-01-01 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BK_Name', models.CharField(max_length=100)),
                ('BK_Phone', models.PositiveIntegerField()),
                ('BK_Email', models.EmailField(max_length=30)),
                ('BK_AadharNo', models.IntegerField()),
                ('BK_travel_date', models.DateField()),
                ('BK_No_of_travelers', models.PositiveIntegerField(default=0)),
                ('BK_time', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 31, 5, 20800, tzinfo=datetime.timezone.utc))),
                ('BK_Status', models.BooleanField(default=0)),
                ('BK_Cancel', models.BooleanField(default=0)),
                ('BK_trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
                ('BK_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserOtp',
            },
        ),
        migrations.CreateModel(
            name='BookingsSubTravellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BKST_Name', models.CharField(max_length=100)),
                ('BKST_Phone', models.PositiveIntegerField()),
                ('BKST_Email', models.EmailField(max_length=30)),
                ('BK_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bookings')),
            ],
            options={
                'db_table': 'BookingsSubTravellers',
            },
        ),
    ]
