# Generated by Django 4.1.4 on 2023-03-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BK_Name', models.CharField(max_length=100)),
                ('BK_Phone', models.PositiveIntegerField()),
                ('BK_Email', models.EmailField(max_length=30)),
                ('BK_travel_date', models.DateField()),
                ('BK_No_of_travelers', models.PositiveIntegerField(default=1)),
                ('BK_Status', models.BooleanField(default=0)),
                ('BK_Cancel', models.BooleanField(default=0)),
                ('BK_trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
                ('BK_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
