# Generated by Django 4.1.4 on 2024-01-01 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='BK_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 34, 23, 653774, tzinfo=datetime.timezone.utc)),
        ),
    ]
