# Generated by Django 4.1.4 on 2024-01-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_bookings_bk_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='BK_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 10, 56, 33, 640581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='UserPfp',
        ),
    ]
