# Generated by Django 4.1.4 on 2023-03-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('trip_type', models.CharField(max_length=100)),
                ('trip_description', models.TextField()),
                ('trip_sublocation', models.CharField(max_length=50)),
                ('trip_location', models.CharField(max_length=50)),
                ('trip_country', models.CharField(max_length=100)),
                ('trip_cost', models.IntegerField(default='999999')),
                ('trip_rating', models.IntegerField(default=0)),
                ('trip_image', models.ImageField(default='', upload_to='images/')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='Trips_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='images/')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trips')),
            ],
            options={
                'db_table': 'trips_images',
            },
        ),
    ]
